# Generated by Django 4.2.9 on 2025-02-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "CKG_NM",
                    models.CharField(max_length=255, null=True, verbose_name="요리명"),
                ),
                ("CKG_MTRL_CN", models.TextField(null=True, verbose_name="재료 목록")),
                (
                    "CKG_INBUN_NM",
                    models.CharField(max_length=50, null=True, verbose_name="인분 수"),
                ),
                (
                    "CKG_TIME_NM",
                    models.CharField(
                        max_length=50, null=True, verbose_name="조리 시간"
                    ),
                ),
                (
                    "RCP_IMG_URL",
                    models.TextField(null=True, verbose_name="레시피 이미지"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="요리명")),
                ("instructions", models.TextField(null=True, verbose_name="조리방법")),
            ],
            options={
                "verbose_name": "레시피",
                "verbose_name_plural": "레시피",
                "db_table": "recipes",
            },
        ),
    ]
