# Generated by Django 4.2.9 on 2025-02-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="요리명")),
                (
                    "image",
                    models.URLField(
                        blank=True, default="", null=True, verbose_name="레시피 이미지"
                    ),
                ),
                (
                    "cook_time",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        null=True,
                        verbose_name="조리 시간",
                    ),
                ),
                (
                    "servings",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="인분 수"
                    ),
                ),
                (
                    "ingredients",
                    models.JSONField(
                        blank=True, default=list, null=True, verbose_name="재료 목록"
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="조리방법"
                    ),
                ),
            ],
            options={
                "verbose_name": "레시피",
                "verbose_name_plural": "레시피",
                "db_table": "recipes",
            },
        ),
    ]
