# Generated by Django 4.2.9 on 2025-02-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("image", models.URLField(blank=True, null=True)),
                ("cook_time", models.CharField(blank=True, max_length=100)),
                ("servings", models.IntegerField(default=1)),
                ("ingredients", models.TextField()),
                ("instructions", models.TextField()),
            ],
        ),
    ]
