# Generated by Django 4.2.9 on 2025-02-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="image",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="name",
        ),
        migrations.AddField(
            model_name="recipe",
            name="image_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="recipe_name",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="cook_time",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="servings",
            field=models.CharField(max_length=50),
        ),
    ]
