# Generated by Django 4.2.9 on 2025-02-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        db_column="SESSION_ID",
                        default="",
                        max_length=100,
                        verbose_name="세션 ID",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        db_column="MSG_CN", default="", verbose_name="대화 내용"
                    ),
                ),
                (
                    "is_user",
                    models.BooleanField(
                        db_column="IS_USER_YN", default=True, verbose_name="사용자 여부"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="CRT_DTM",
                        null=True,
                        verbose_name="생성 시간",
                    ),
                ),
            ],
            options={
                "verbose_name": "대화 기록",
                "verbose_name_plural": "대화 기록",
                "db_table": "chat_logs",
                "ordering": ["timestamp"],
            },
        ),
    ]
