# Generated by Django 4.2.9 on 2025-02-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatlog",
            name="session_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
