# Generated by Django 4.2.9 on 2025-02-24 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0002_chatlog_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatlog",
            name="session_id",
            field=models.CharField(
                db_column="SESSION_ID",
                default="",
                max_length=100,
                verbose_name="세션 ID",
            ),
        ),
    ]
